# This file is a template, and might need editing before it works on your project.
image: ayufan/openshift-cli

stages:
  - test
  - review
  - staging


variables:
  OPENSHIFT_SERVER: console.starter-us-east-1.openshift.com
  OPENSHIFT_DOMAIN: jfrog-codingchallenge
  # Configure this variable in Secure Variables:
  # OPENSHIFT_TOKEN: my.openshift.token

test1:
  stage: test
  before_script: []
  script:
    - echo run tests

test2:
  stage: test
  before_script: []
  script:
    - echo run tests

.deploy: &deploy
  before_script:
    - oc login https://api.starter-us-east-1.openshift.com --token=8-mDrpPUQDhB7lVaMKx8vfoEo2fwcyPQ-P3qA7MeMio --insecure-skip-tls-verify
    - oc project "$CI_PROJECT_NAME"
  script:
    - "oc start-build openjdk-app -n jfrog-codingchallenge"
staging:
  <<: *deploy
  stage: staging
  variables:
    APP: staging
    APP_HOST: $CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  only:
    - master

