image: docker:stable


variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

services:
  - docker:dind  


stages:
  - build


k8s-deploy:
  image: google/cloud-sdk
  stage: build
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-west1-b
  - gcloud config set project virtual-ego-235417
  - gcloud config set container/use_client_certificate True
  - gcloud services enable container.googleapis.com
  - gcloud container clusters get-credentials jfrog-codingchalenge-cluster
  - gcloud config unset container/use_client_certificate
  - kubectl config use-context gke_virtual-ego-235417_us-west1-b-jfrog-codingchalenge-cluster
  - kubectl delete secret registry.gitlab.com
  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=sdugyal --docker-password=$REGISTRY_PASSWD --docker-email=dugyala.srikanth.rao@gmail.com
  - kubectl apply -f deployment.yml

