apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: gitlab-managed-apps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  
spec:
  backend:
    serviceName: jfrog-cc-service
    servicePort: 8080
  rules:
  - host: jfrog-gitlab-codingchallge.gcp.com
    http:
      paths:
      - backend:
          serviceName: jfrog-codingchalenge-cluster
          servicePort: 8080
  - host: jfrog-gitlab-codingchallge.gcp.com
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: jfrog-codingchalenge-cluster
          servicePort: 8080   
    