apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"name":"ingress-resource","namespace":"gitlab-managed-apps"},"spec":{"backend":{"serviceName":"jfrog-cc-service","servicePort":8080},"rules":[{"host":"jfrog-gitlab-codingchallge.gcp.com","http":{"paths":[{"backend":{"serviceName":"jfrog-cc-service","servicePort":8080}}]}},{"host":"jfrog-gitlab-codingchallge.gcp.com","http":{"paths":[{"backend":{"serviceName":"jfrog-cc-service","servicePort":8080},"path":"/api/*"}]}}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: 2019-03-25T20:44:27Z
  generation: 6
  name: ingress-resource
  namespace: gitlab-managed-apps
  resourceVersion: "195714"
  selfLink: /apis/extensions/v1beta1/namespaces/gitlab-managed-apps/ingresses/ingress-resource
  uid: c84adf80-4f3e-11e9-aa83-42010a8a0111
spec:
  rules:
    http:
      paths: /*
      - backend:
          serviceName: jfrog-codingchalenge-cluster
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 35.227.190.7